# Generated by Django 3.1.6 on 2021-02-28 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(default='0', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=24, max_digits=25)),
                ('weakest_link', models.CharField(max_length=200)),
                ('No_1_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_2_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_3_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_4_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_5_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_6_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_7_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_8_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_9_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_10_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_11_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_12_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_13_Angle_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_1_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_2_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_3_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_4_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_5_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_6_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_7_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_8_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_9_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_10_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_11_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_12_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_13_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_14_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_15_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_16_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_17_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_18_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_19_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_20_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_21_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_22_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_23_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_24_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_25_NASM_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_1_Time_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('No_2_Time_Deviation', models.DecimalField(decimal_places=24, max_digits=25)),
                ('aimoscore', models.DecimalField(blank=True, decimal_places=24, max_digits=25, null=True)),
                ('estimatedscore', models.DecimalField(blank=True, decimal_places=24, max_digits=25, null=True)),
            ],
        ),
    ]
